version: '3.8'
services:
  testdb:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3307:3306'
