version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: study
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=study
      - AWS_ACCESS_KEY=AKIA6PBTDJ55BIWZXHEH
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-northeast-2
      - CLOUDWATCH_GROUP_NAME=ecs-study-production
      - CLOUDWATCH_STREAM_INFO=info
      - CLOUDWATCH_STREAM_ERROR=error
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./src/:/src/
    depends_on:
      - db
